/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentCallbackRouteImport } from './routes/payment-callback'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardAdminRouteImport } from './routes/dashboard-admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard-admin.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard-admin.users'
import { Route as DashboardAdminReferralsRouteImport } from './routes/dashboard-admin.referrals'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/dashboard-admin.payments'
import { Route as DashboardAdminLoginRouteImport } from './routes/dashboard-admin.login'
import { Route as DashboardAdminAnalyticsRouteImport } from './routes/dashboard-admin.analytics'
import { Route as AppUpgradeRouteImport } from './routes/app.upgrade'
import { Route as AppTimerRouteImport } from './routes/app.timer'
import { Route as AppSubjectsRouteImport } from './routes/app.subjects'
import { Route as AppStreaksRouteImport } from './routes/app.streaks'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppReadinessRouteImport } from './routes/app.readiness'
import { Route as AppLogRouteImport } from './routes/app.log'
import { Route as AppInviteRouteImport } from './routes/app.invite'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as ApiPublicKashierWebhookRouteImport } from './routes/api/public/kashier-webhook'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment-callback',
  path: '/payment-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard-admin',
  path: '/dashboard-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminReferralsRoute = DashboardAdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminLoginRoute = DashboardAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAnalyticsRoute = DashboardAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppTimerRoute = AppTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppStreaksRoute = AppStreaksRouteImport.update({
  id: '/streaks',
  path: '/streaks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppReadinessRoute = AppReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AppRoute,
} as any)
const AppLogRoute = AppLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteRoute = AppInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicKashierWebhookRoute = ApiPublicKashierWebhookRouteImport.update({
  id: '/api/public/kashier-webhook',
  path: '/api/public/kashier-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard-admin': typeof DashboardAdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/invite': typeof AppInviteRoute
  '/app/log': typeof AppLogRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/streaks': typeof AppStreaksRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/timer': typeof AppTimerRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/dashboard-admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard-admin/login': typeof DashboardAdminLoginRoute
  '/dashboard-admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard-admin/referrals': typeof DashboardAdminReferralsRoute
  '/dashboard-admin/users': typeof DashboardAdminUsersRoute
  '/app/': typeof AppIndexRoute
  '/dashboard-admin/': typeof DashboardAdminIndexRoute
  '/api/public/kashier-webhook': typeof ApiPublicKashierWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/invite': typeof AppInviteRoute
  '/app/log': typeof AppLogRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/streaks': typeof AppStreaksRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/timer': typeof AppTimerRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/dashboard-admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard-admin/login': typeof DashboardAdminLoginRoute
  '/dashboard-admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard-admin/referrals': typeof DashboardAdminReferralsRoute
  '/dashboard-admin/users': typeof DashboardAdminUsersRoute
  '/app': typeof AppIndexRoute
  '/dashboard-admin': typeof DashboardAdminIndexRoute
  '/api/public/kashier-webhook': typeof ApiPublicKashierWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard-admin': typeof DashboardAdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/invite': typeof AppInviteRoute
  '/app/log': typeof AppLogRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/streaks': typeof AppStreaksRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/timer': typeof AppTimerRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/dashboard-admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard-admin/login': typeof DashboardAdminLoginRoute
  '/dashboard-admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard-admin/referrals': typeof DashboardAdminReferralsRoute
  '/dashboard-admin/users': typeof DashboardAdminUsersRoute
  '/app/': typeof AppIndexRoute
  '/dashboard-admin/': typeof DashboardAdminIndexRoute
  '/api/public/kashier-webhook': typeof ApiPublicKashierWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard-admin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/payment-callback'
    | '/payment-success'
    | '/refund'
    | '/reset-password'
    | '/signup'
    | '/upgrade'
    | '/app/analytics'
    | '/app/invite'
    | '/app/log'
    | '/app/readiness'
    | '/app/schedule'
    | '/app/settings'
    | '/app/streaks'
    | '/app/subjects'
    | '/app/timer'
    | '/app/upgrade'
    | '/dashboard-admin/analytics'
    | '/dashboard-admin/login'
    | '/dashboard-admin/payments'
    | '/dashboard-admin/referrals'
    | '/dashboard-admin/users'
    | '/app/'
    | '/dashboard-admin/'
    | '/api/public/kashier-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/payment-callback'
    | '/payment-success'
    | '/refund'
    | '/reset-password'
    | '/signup'
    | '/upgrade'
    | '/app/analytics'
    | '/app/invite'
    | '/app/log'
    | '/app/readiness'
    | '/app/schedule'
    | '/app/settings'
    | '/app/streaks'
    | '/app/subjects'
    | '/app/timer'
    | '/app/upgrade'
    | '/dashboard-admin/analytics'
    | '/dashboard-admin/login'
    | '/dashboard-admin/payments'
    | '/dashboard-admin/referrals'
    | '/dashboard-admin/users'
    | '/app'
    | '/dashboard-admin'
    | '/api/public/kashier-webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard-admin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/payment-callback'
    | '/payment-success'
    | '/refund'
    | '/reset-password'
    | '/signup'
    | '/upgrade'
    | '/app/analytics'
    | '/app/invite'
    | '/app/log'
    | '/app/readiness'
    | '/app/schedule'
    | '/app/settings'
    | '/app/streaks'
    | '/app/subjects'
    | '/app/timer'
    | '/app/upgrade'
    | '/dashboard-admin/analytics'
    | '/dashboard-admin/login'
    | '/dashboard-admin/payments'
    | '/dashboard-admin/referrals'
    | '/dashboard-admin/users'
    | '/app/'
    | '/dashboard-admin/'
    | '/api/public/kashier-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UpgradeRoute: typeof UpgradeRoute
  ApiPublicKashierWebhookRoute: typeof ApiPublicKashierWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-callback': {
      id: '/payment-callback'
      path: '/payment-callback'
      fullPath: '/payment-callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-admin': {
      id: '/dashboard-admin'
      path: '/dashboard-admin'
      fullPath: '/dashboard-admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-admin/': {
      id: '/dashboard-admin/'
      path: '/'
      fullPath: '/dashboard-admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/dashboard-admin/users': {
      id: '/dashboard-admin/users'
      path: '/users'
      fullPath: '/dashboard-admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard-admin/referrals': {
      id: '/dashboard-admin/referrals'
      path: '/referrals'
      fullPath: '/dashboard-admin/referrals'
      preLoaderRoute: typeof DashboardAdminReferralsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard-admin/payments': {
      id: '/dashboard-admin/payments'
      path: '/payments'
      fullPath: '/dashboard-admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard-admin/login': {
      id: '/dashboard-admin/login'
      path: '/login'
      fullPath: '/dashboard-admin/login'
      preLoaderRoute: typeof DashboardAdminLoginRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard-admin/analytics': {
      id: '/dashboard-admin/analytics'
      path: '/analytics'
      fullPath: '/dashboard-admin/analytics'
      preLoaderRoute: typeof DashboardAdminAnalyticsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timer': {
      id: '/app/timer'
      path: '/timer'
      fullPath: '/app/timer'
      preLoaderRoute: typeof AppTimerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects': {
      id: '/app/subjects'
      path: '/subjects'
      fullPath: '/app/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/streaks': {
      id: '/app/streaks'
      path: '/streaks'
      fullPath: '/app/streaks'
      preLoaderRoute: typeof AppStreaksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/readiness': {
      id: '/app/readiness'
      path: '/readiness'
      fullPath: '/app/readiness'
      preLoaderRoute: typeof AppReadinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/log': {
      id: '/app/log'
      path: '/log'
      fullPath: '/app/log'
      preLoaderRoute: typeof AppLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invite': {
      id: '/app/invite'
      path: '/invite'
      fullPath: '/app/invite'
      preLoaderRoute: typeof AppInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/kashier-webhook': {
      id: '/api/public/kashier-webhook'
      path: '/api/public/kashier-webhook'
      fullPath: '/api/public/kashier-webhook'
      preLoaderRoute: typeof ApiPublicKashierWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppInviteRoute: typeof AppInviteRoute
  AppLogRoute: typeof AppLogRoute
  AppReadinessRoute: typeof AppReadinessRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStreaksRoute: typeof AppStreaksRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppTimerRoute: typeof AppTimerRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppInviteRoute: AppInviteRoute,
  AppLogRoute: AppLogRoute,
  AppReadinessRoute: AppReadinessRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStreaksRoute: AppStreaksRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppTimerRoute: AppTimerRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DashboardAdminRouteChildren {
  DashboardAdminAnalyticsRoute: typeof DashboardAdminAnalyticsRoute
  DashboardAdminLoginRoute: typeof DashboardAdminLoginRoute
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute
  DashboardAdminReferralsRoute: typeof DashboardAdminReferralsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAnalyticsRoute: DashboardAdminAnalyticsRoute,
  DashboardAdminLoginRoute: DashboardAdminLoginRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
  DashboardAdminReferralsRoute: DashboardAdminReferralsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UpgradeRoute: UpgradeRoute,
  ApiPublicKashierWebhookRoute: ApiPublicKashierWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
